### ISSUE TITLE
Seeds is broken

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/library_hours_rails#424]
```
bin/rails db:seed
rails aborted!
ActiveRecord::RecordNotFound: Couldn't find Location with 'id'=37
/Users/jcoyne85/workspace/sul-dlss/library_hours_rails/db/seeds.rb:86:in `block in <main>'
/Users/jcoyne85/workspace/sul-dlss/library_hours_rails/db/seeds.rb:85:in `each'
/Users/jcoyne85/workspace/sul-dlss/library_hours_rails/db/seeds.rb:85:in `<main>'
Tasks: TOP => db:seed
```

**Comment by jcoyne** [comment]
Fixed by #425
